import "server-only"

import ContextWrapper from "@/Context/ContextWrapper"
import { Colors } from "@/Shared/colors"
// import { backgroundColorLight, textColorLight } from "@/Shared/colors"
import style from "@/Shared/css/styles"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// async function getData() {
//   // const res = await fetch('https://jsonplaceholder.typicode.com/todos');
//   // const res = await fetch('https://api.quotable.io/random/');
//   const res = await fetch('https://randomuser.me/api/');

//   return res.json();
// }


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const table = await getData();

  const getColors = Colors()

  return (
    <html lang="en">

      <body
        style={{
          width: "100%", height: "100%",
          overflowX: "hidden",

          backgroundImage: getColors.backgroundColor,

          backgroundSize: "300% 300%",
          animation: `${style.AnimateBG} 7s ease infinite`,

          color: getColors.textColor,
        }}
        className={style.HiddenScrollBar}
      >

        <ContextWrapper >

          {children}
        </ContextWrapper>

      </body>

    </html>
  )
}