import "server-only"

import ContextWrapper from "@/Context/ContextWrapper"
import { Colors } from "@/Shared/colors"
import styles from "@/Shared/css/styles"

export const metadata = {
  title: "Toxy's Portfolio",
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const getColors = Colors()

  return (
    <html lang="en">

      <body
        style={{
          width: "100%", height: "100%",
          overflowX: "hidden",

          backgroundImage: getColors.bodyBackground,

          backgroundSize: "300% 300%",
          animation: `${styles.AnimateBG} 7s ease infinite`,

          color: getColors.textColor,
        }}
        className={styles.HiddenScrollBar}
      >

        <ContextWrapper>
          {children}
        </ContextWrapper>

      </body>

    </html>
  )
}